//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Music
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADMIN
    {
        public string TenAD { get; set; }
        public string UserName { get; set; }
        public string Pass { get; set; }
        public Nullable<bool> TrangThai { get; set; }
        public string DC { get; set; }
        public Nullable<decimal> SDT { get; set; }
        public Nullable<decimal> STK { get; set; }
        public Nullable<bool> GT { get; set; }
        public Nullable<System.DateTime> NS { get; set; }
        public string Email { get; set; }
        public string URL_img { get; set; }
        public string GhiChu { get; set; }
        public string MaAD { get; set; }
    }
}
