//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Music
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHACH_HANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KHACH_HANG()
        {
            this.ALbums = new HashSet<ALbum>();
            this.NGHEs = new HashSet<NGHE>();
            this.THEO_DOI = new HashSet<THEO_DOI>();
            this.TRUY_CAP_TM = new HashSet<TRUY_CAP_TM>();
            this.YEU_THICH = new HashSet<YEU_THICH>();
        }
    
        public string TenKH { get; set; }
        public string URL_img { get; set; }
        public string UserName { get; set; }
        public string Pass { get; set; }
        public string DiaChi { get; set; }
        public decimal SDT { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public Nullable<bool> TrangThai { get; set; }
        public Nullable<bool> GT { get; set; }
        public decimal CCCD { get; set; }
        public string Email { get; set; }
        public string GhiChu { get; set; }
        public string MaKH { get; set; }
        public int ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ALbum> ALbums { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NGHE> NGHEs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<THEO_DOI> THEO_DOI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRUY_CAP_TM> TRUY_CAP_TM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<YEU_THICH> YEU_THICH { get; set; }
    }
}
