//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Music
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WebMusicEntities1 : DbContext
    {
        public WebMusicEntities1()
            : base("name=WebMusicEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ADMIN> ADMINs { get; set; }
        public virtual DbSet<ALbum> ALbums { get; set; }
        public virtual DbSet<KHACH_HANG> KHACH_HANG { get; set; }
        public virtual DbSet<NGHE> NGHEs { get; set; }
        public virtual DbSet<NGHE_SI> NGHE_SI { get; set; }
        public virtual DbSet<SAN_PHAM> SAN_PHAM { get; set; }
        public virtual DbSet<THEO_DOI> THEO_DOI { get; set; }
        public virtual DbSet<TIN_MOI> TIN_MOI { get; set; }
        public virtual DbSet<TRINH_BAY> TRINH_BAY { get; set; }
        public virtual DbSet<TRUY_CAP_TM> TRUY_CAP_TM { get; set; }
        public virtual DbSet<YEU_THICH> YEU_THICH { get; set; }
    }
}
