//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Music
{
    using System;
    using System.Collections.Generic;
    
    public partial class NGHE_SI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NGHE_SI()
        {
            this.THEO_DOI = new HashSet<THEO_DOI>();
            this.TRINH_BAY = new HashSet<TRINH_BAY>();
        }
    
        public string TenNS { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string QueQuan { get; set; }
        public string NS_URL { get; set; }
        public Nullable<bool> GT { get; set; }
        public string GhiChu { get; set; }
        public Nullable<decimal> TheoDoi { get; set; }
        public string NgheDanh { get; set; }
        public string URL_img { get; set; }
        public string mans { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<THEO_DOI> THEO_DOI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRINH_BAY> TRINH_BAY { get; set; }
    }
}
