//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Music
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAN_PHAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SAN_PHAM()
        {
            this.NGHEs = new HashSet<NGHE>();
            this.TRINH_BAY = new HashSet<TRINH_BAY>();
            this.YEU_THICH = new HashSet<YEU_THICH>();
            this.ALbums = new HashSet<ALbum>();
        }
    
        public string TenSP { get; set; }
        public string SangTac { get; set; }
        public string SP_URL { get; set; }
        public string Theloai { get; set; }
        public Nullable<bool> TrangThai { get; set; }
        public Nullable<double> LuotNghe { get; set; }
        public string GhiChu { get; set; }
        public Nullable<decimal> YeuThich { get; set; }
        public Nullable<decimal> KhongYeuThich { get; set; }
        public Nullable<System.DateTime> TGPhatHanh { get; set; }
        public string MaSP { get; set; }
        public Nullable<System.TimeSpan> ThoiGian { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NGHE> NGHEs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRINH_BAY> TRINH_BAY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<YEU_THICH> YEU_THICH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ALbum> ALbums { get; set; }
    }
}
