//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Music
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIN_MOI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TIN_MOI()
        {
            this.TRUY_CAP_TM = new HashSet<TRUY_CAP_TM>();
        }
    
        public string TenTM { get; set; }
        public Nullable<System.DateTime> ThoiGian { get; set; }
        public string URL_img { get; set; }
        public string URL_link { get; set; }
        public string GhiChu { get; set; }
        public Nullable<double> LuotTruyCap { get; set; }
        public string MaTM { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRUY_CAP_TM> TRUY_CAP_TM { get; set; }
    }
}
