//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Music
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRUY_CAP_TM
    {
        public string makh { get; set; }
        public string maTM { get; set; }
        public System.DateTime ThoiGian { get; set; }
    
        public virtual KHACH_HANG KHACH_HANG { get; set; }
        public virtual TIN_MOI TIN_MOI { get; set; }
    }
}
