//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Music
{
    using System;
    using System.Collections.Generic;
    
    public partial class YEU_THICH
    {
        public string makh { get; set; }
        public string masp { get; set; }
        public Nullable<System.DateTime> ThoiGian { get; set; }
        public Nullable<bool> YeuThich { get; set; }
    
        public virtual KHACH_HANG KHACH_HANG { get; set; }
        public virtual SAN_PHAM SAN_PHAM { get; set; }
    }
}
